### ISSUE TITLE
NotSupportedException: No IUserTokenProvider named  is registered.

### ISSUE THREAD

**Issue by capiono** [aspnet/Identity#1035]
Hello, I'm getting an error when I try to generate a Token:

```userManager.GenerateTwoFactorTokenAsync```

Exception:
```NotSupportedException: No IUserTokenProvider named '' is registered. 
at Microsoft.AspNetCore.Identity.UserManager`1.GenerateTwoFactorTokenAsync(TUser user, String tokenProvider)
   at AccountController.<SendCode>d__20.MoveNext() in AccountController.cs:line 297
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()```

I tried registering the providers manually as suggested [here](https://github.com/aspnet/Identity/issues/1018)

but I got the same error.

I'm using ```Microsoft.AspNetCore.Identity": "1.1.0```

**Comment by AurelianGaiu** [comment]
Hello @capiono did you solved the problem because i've tried also using the same method as [here](https://github.com/aspnet/Identity/issues/1018) but with no result.
