### ISSUE TITLE
UserRole table name does not change after inheriting form IdentityUserRole

### ISSUE THREAD

**Issue by per3ian** [aspnet/Identity#1310]
I could change IdentityCore tables name before. I used this code before and it worked.

```
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.Entity<ApplicationUser>().ToTable("Users");
            builder.Entity<IdentityRole>().ToTable("Roles");
            builder.Entity<IdentityUserRole<string>>().ToTable("UserRoles");
            builder.Entity<IdentityUserLogin<string>>().ToTable("UserLogins");
            builder.Entity<IdentityUserClaim<string>>().ToTable("UserClaims");
            builder.Entity<IdentityUserToken<string>>().ToTable("UserTokens");
            builder.Entity<IdentityRoleClaim<string>>().ToTable("RoleClaims");
        }
```

but I needed to add some new properties to UserRole table. so I created a class and I inherited from IdentityUserRole<string> . now it added my properties but it does not changed table name. it changed to default name after inheriting. this is my class code :

```
    public class ApplicationUsersJoinsRoles : IdentityUserRole<string>
    {
        public string NickName { get; set; }
    }
```

and this is my modelbuilder : 

```
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.Entity<ApplicationUser>().ToTable("Users");
            builder.Entity<IdentityRole>().ToTable("Roles");
            builder.Entity<ApplicationUsersJoinsRoles>().ToTable("UsersJoinsRoles");
            builder.Entity<IdentityUserLogin<string>>().ToTable("UserLogins");
            builder.Entity<IdentityUserClaim<string>>().ToTable("UserClaims");
            builder.Entity<IdentityUserToken<string>>().ToTable("UserTokens");
            builder.Entity<IdentityRoleClaim<string>>().ToTable("RoleClaims");
        }

```

**Comment by blowdart** [comment]
Which version are you using?
Can we see your AddIdentity pieces and related calls from startup?

**Comment by smithaitufe** [comment]
I am having an error with relation to UserRole as well. Here is the error

```
Npgsql.PostgresException (0x80004005): 42P01: relation "Roles" does not exist
   at Npgsql.NpgsqlConnector.<DoReadMessage>d__148.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__147.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__147.MoveNext()
```
I am using DotnetCore 2.0.0 Preview2. I did not have this error in Preview1


Here are my classes
User.cs
```
public class User : IdentityUser<int>
    {
        public string LibraryNo { get; set; }
        [Required]
        [MaxLength(50)]
        public string FirstName { get; set; }
        [Required]
        [MaxLength(50)]
        public string LastName { get; set; }
        public Image Photo { get; set; }
        public DateTime InsertedAt { get; private set;} = DateTime.Now;
        public bool ChangePasswordFirstTimeLogin { get; set; } = false;
        public bool Approved { get; set; }
        public bool Suspended { get; set; } = false;
        public bool Locked { get; set; } = false;
        [NotMapped]
        public string FullName => $"{LastName} {FirstName}";
        public ICollection<UserLocation> LocationsLink { get; set; } = new HashSet<UserLocation>();
        public ICollection<Post> Posts { get; set; } = new HashSet<Post>();
        public ICollection<Comment> Comments { get; set; }
        public ICollection<UserAddress> AddressesLink { get; set; } = new HashSet<UserAddress>();

        public ICollection<Reservation> Reservations { get; set; }
        public ICollection<Reservation> ReservationBookings { get; set; }

        public ICollection<CheckOutState> CheckOutStates { get; set; }
        public ICollection<Recall> RecalledBooks { get; set; }        
    }
```
Role.cs
```
public class Role : IdentityRole<int>
    {}
```

**Comment by per3ian** [comment]
@blowdart This is my ConfigureServices section : 

```
services.AddIdentity<ApplicationUser, IdentityRole>()
                   .AddEntityFrameworkStores<xDbContext>()
                   .AddDefaultTokenProviders();

            services.Configure<IdentityOptions>(options =>
            {
                // Password settings
                options.Password.RequireDigit = false;
                options.Password.RequiredLength = 4;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = false;
                options.Password.RequireLowercase = false;

                // Lockout settings
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(30);
                options.Lockout.MaxFailedAccessAttempts = 10;

                // Cookie settings
                options.Cookies.ApplicationCookie.ExpireTimeSpan = TimeSpan.FromDays(150);
                options.Cookies.ApplicationCookie.LoginPath = "/Login";
                options.Cookies.ApplicationCookie.LogoutPath = "/Login/LogOff";

                // User settings
                options.User.RequireUniqueEmail = false;
            });
```

**Comment by blowdart** [comment]
@HaoK can you take a look?

**Comment by HaoK** [comment]
@per3ian please also include your ApplicationUser and xDbContext classes

**Comment by per3ian** [comment]
@HaoK @blowdart  this is my applicationUser class :

```
    // Add profile data for application users by adding properties to the ApplicationUser class
    public class ApplicationUser : IdentityUser
    {
        public ApplicationUser()
        {

        }

        public string Name { get; set; }                                 

        public string About { get; set; }                               

        public string CellPhoneNumber { get; set; }                     

        public byte? Gender { get; set; }                                

        public string Photo { get; set; }                               

        public int ExSegmentId { get; set; }
        public virtual Segment Segment { get; set; }

    }
    public class AppClaimsPrincipalFactory : UserClaimsPrincipalFactory<ApplicationUser, IdentityRole>
    {
        public AppClaimsPrincipalFactory(
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager,
            IOptions<IdentityOptions> optionsAccessor) : base(userManager, roleManager, optionsAccessor)
        {
        }

        public async override Task<ClaimsPrincipal> CreateAsync(ApplicationUser user)
        {
            var principal = await base.CreateAsync(user);

            ((ClaimsIdentity)principal.Identity)
                .AddClaims(new[] {
                new Claim("Id", user.Id),
                new Claim("Name", user.Name),
            });

            return principal;
        }
    }
```

and my dbcontext :

```
    public class xDbContext : IdentityDbContext<ApplicationUser>, IUnitOfWork
    {

        public readonly IConfigurationRoot _configuration;

        public xDbContext(IConfigurationRoot configuration)
        {
            _configuration = configuration;
        }

        public xDbContext()
        {}

        public DbSet<Place> Places { get; set; }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            new PlaceMap(builder.Entity<Place>());

            builder.Entity<ApplicationUser>().ToTable("Users");
            builder.Entity<IdentityRole>().ToTable("Roles");
            builder.Entity<ApplicationUsersJoinsRoles>().ToTable("UsersJoinsRoles");
            builder.Entity<IdentityUserLogin<string>>().ToTable("UserLogins");
            builder.Entity<IdentityUserClaim<string>>().ToTable("UserClaims");
            builder.Entity<IdentityUserToken<string>>().ToTable("UserTokens");
            builder.Entity<IdentityRoleClaim<string>>().ToTable("RoleClaims");
        }

        protected override void OnConfiguring(DbContextOptionsBuilder b)
        {
            string ConnectionString = "ConnectionStrings:DefaultConnection";

            b.UseSqlServer(
                _configuration[ConnectionString],
                serverDbContextOptionsBuilder =>
                {
                    var minutes = (int)TimeSpan.FromMinutes(3).TotalSeconds;
                    serverDbContextOptionsBuilder.CommandTimeout(minutes);
                });
        }

        public void AddRange<TEntity>(IEnumerable<TEntity> entities) where TEntity : class
        {
            base.Set<TEntity>().AddRange(entities);
        }

        public void RemoveRange<TEntity>(IEnumerable<TEntity> entities) where TEntity : class
        {
            base.Set<TEntity>().RemoveRange(entities);
        }

        public void MarkAsChanged<TEntity>(TEntity entity) where TEntity : class
        {
            base.Entry(entity).State = EntityState.Modified; // Or use ---> this.Update(entity);
        }

        public void ExecuteSqlCommand(string query)
        {
            base.Database.ExecuteSqlCommand(query);
        }

        public void ExecuteSqlCommand(string query, params object[] parameters)
        {
            base.Database.ExecuteSqlCommand(query, parameters);
        }

        public int SaveAllChanges()
        {
            return base.SaveChanges();
        }

        public void Rollback()
        {
            base.Database.RollbackTransaction();
        }

        public Task<int> SaveAllChangesAsync()
        {
            return base.SaveChangesAsync();
        }
    }
```

**Comment by per3ian** [comment]
@blowdart @HaoK  any news?

**Comment by per3ian** [comment]
I fixed this by adding IdentityUserRole after inherited class in my dbContext like this :

```
            // To add extra fields to UserRoles table.
            builder.Entity<ApplicationUsersJoinsRoles>().ToTable("UsersJoinsRoles");
            builder.Entity<IdentityUserRole<int>>().ToTable("UsersJoinsRoles");
```

I dont know why but it works!
I mean my own fields added and table name changed!

**Comment by blowdart** [comment]
OK closing because you've got it working :)
