### ISSUE TITLE
Changing datatype of primary key 

### ISSUE THREAD

**Issue by bhubanstha** [aspnet/Identity#1397]
Shouldn't we consider changing string or guid datatype to int for PK in identity. Well there might be some cases where guid or string PK is unavoidable but I think most of us use int for PK. So leaving string/guid as PK one has to create lots of identity related classes wasting time that was supposed to minimize by identity. I personally feel if int was used instead of string one can start writing other code instead of customizing identity classes for his/her desired datatype just for PK.

**Comment by AdrienTorris** [comment]
Our primary keys datatype is not the business of Microsoft, it's the reason why the default pk type in Identity is string, who is the less restrictive datatype format. It's a design choice.

But you can easily override the data type of the primary keys in identity without customize the classes, the 2min procedure is explained here : https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-primary-key-configuration

**Comment by chadwackerman2** [comment]
@AdrienTorris unfortunately that's broken as of 2.0.0.

Also: it's not 2003 any more. Identity should take a generic of the PK type you want -- string, int or guid -- and it should just work. There's acres of stackoverflow posts where people try to get this simple thing working. Given the confusion it's obviously a non-intuitive and poorly-documented design. And as of 2.0 untested, too.

@bhubanstha isn't really asking for "int" to be the default. He's asking to avoid all this weirdo grunt work just to use int. And he's right to do so.

**Comment by bhubanstha** [comment]
@AdrienTorris the documentation link you have provided seems to provide configuration details for previous version of Identity. I am using Identity in .NET Core 2.0 so following tutorial in provided doc gives me error which is as follows

```
Unhandled Exception: System.ArgumentException: GenericArguments[1], 'Microsoft.AspNetCore.Identity.IdentityRole', on 'Microsoft.AspNetCore.Identity.Entity
FrameworkCore.UserStore`9[TUser,TRole,TContext,TKey,TUserClaim,TUserRole,TUserLogin,TUserToken,TRoleClaim]' violates the constraint of type 'TRole'. --->
System.TypeLoadException: GenericArguments[1], 'Microsoft.AspNetCore.Identity.IdentityRole', on 'Microsoft.AspNetCore.Identity.UserStoreBase`8[TUser,TRole
,TKey,TUserClaim,TUserRole,TUserLogin,TUserToken,TRoleClaim]' violates the constraint of type parameter 'TRole'.
   at System.RuntimeTypeHandle.Instantiate(RuntimeTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.Instantiate(Type[] inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   --- End of inner exception stack trace ---
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Microsoft.Extensions.DependencyInjection.IdentityEntityFrameworkBuilderExtensions.AddStores(IServiceCollection services, Type userType, Type roleTyp
e, Type contextType)
   at Microsoft.Extensions.DependencyInjection.IdentityEntityFrameworkBuilderExtensions.AddEntityFrameworkStores[TContext](IdentityBuilder builder)
   at AuTest.Startup.ConfigureServices(IServiceCollection services) in E:\Code\AuTest\Startup.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at AuTest.Program.BuildWebHost(String[] args) in E:\Code\AuTest\Program.cs:line 21
   at AuTest.Program.Main(String[] args) in E:\Code\AuTest\Program.cs:line 17
```

Provided approach would be great but unfortunately that didn't work.

**Comment by AdrienTorris** [comment]
Hum you're right the link I sent to you is out to date.
This migration documentation should help you : https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x
And this thread too : https://github.com/aspnet/Identity/issues/1364
Is your source code on GitHub ?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
