### ISSUE TITLE
Functional test discovery fails on build

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Identity#1574]
Fails both locally and on the CI. From http://aspnetci/viewLog.html?buildId=387311&buildTypeId=Lite_Identity&tab=buildLog&_focus=407#_state=407: 

```C#
[Step 4/6] [xUnit.net 00:00:00.2707368] Exception discovering tests from Microsoft.AspnetCore.Identity.Service.FunctionalTests: System.BadImageFormatException: Could not load file or assembly 'Microsoft.AspnetCore.Identity.Service.FunctionalTests, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.
[13:07:57]	[Step 4/6] File name: 'Microsoft.AspnetCore.Identity.Service.FunctionalTests, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
[13:07:57]	[Step 4/6] at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
[13:07:57]	[Step 4/6] at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
[13:07:57]	[Step 4/6] at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
[13:07:57]	[Step 4/6] at Xunit.Sdk.ReflectionAssemblyInfo..ctor(String assemblyFileName) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Reflection\ReflectionAssemblyInfo.cs:line 31
[13:07:57]	[Step 4/6] --- End of stack trace from previous location where exception was thrown ---
[13:07:57]	[Step 4/6] at Xunit.AppDomainManager_NoAppDomain.CreateObject[TObject](AssemblyName assemblyName, String typeName, Object[] args) in C:\Dev\xunit\xunit\src\xunit.runner.utility\AppDomain\AppDomainMan
```

**Comment by pranavkm** [comment]
@javiercn this is caused by the Mvc test target overriding the SDK's platform selection - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Testing/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Testing.targets#L19-L20. The issue that you're attempting to workaround has been fixed. Can you verify that you still need the target?

**Comment by pranavkm** [comment]
https://github.com/dotnet/sdk/issues/1729 might also be a result of the test target. Can you investigate \ close if it's an issue with Mvc's target and not the SDK?

**Comment by javiercn** [comment]
This is done I believe. Closing as no further action is required.
