### ISSUE TITLE
Flaky tests: BadData

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Identity#1630]
http://aspnetci/httpAuth/app/rest/builds?locator=tag:BadData,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)

The above link lists a set of builds which have failed due to an exception thrown from the Identity `CryptographyHelpers` class. They don't seem to be isolated to a particular set of tests, or to a particular machine, but they happen quite frequently for some configurations (such as [Win2012-EF](http://aspnetci/viewType.html?buildTypeId=Lite_EntityFrameworkTest&tab=buildTypeHistoryList&branch_XPlat=__all_branches__)).

cc @javiercn

**Comment by ryanbrandenburg** [comment]
An example failure:
```
System.Security.Cryptography.CryptographicException : Bad Data.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.Utils._ImportKey(SafeProvHandle hCSP, Int32 keyNumber, CspProviderFlags flags, Object cspObject, SafeKeyHandle& hKey)
   at System.Security.Cryptography.RSACryptoServiceProvider.ImportParameters(RSAParameters parameters)
   at Microsoft.AspNetCore.Identity.Service.CryptographyHelpers.GetRSAParameters(SigningCredentials credentials)
   at Microsoft.AspNetCore.Identity.Service.Core.DefaultSigningCredentialsSource.GetMetadata(SigningCredentials credentials)
   at Microsoft.AspNetCore.Identity.Service.Core.DefaultSigningCredentialsSource.<GetDescriptors>b__4_0(SigningCredentials sk)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at Microsoft.AspNetCore.Identity.Service.DefaultSigningCredentialsPolicyProvider.<<GetAllCredentialsAsync>g__RetrieveCredentials|5_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.Service.DefaultSigningCredentialsPolicyProvider.<GetAllCredentialsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.Service.DefaultSigningCredentialsPolicyProvider.<GetSigningCredentialsAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Identity.Service.JwtIdTokenIssuer.<IssueIdTokenAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.Service.TokenManager.<IssueTokensAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Identity.Service.AuthorizationCodeExchangeIntegrationTest.<ValidAuthorizationCode_ProducesAccessTokenIdTokenAndRefreshToken>d__0.MoveNext() in C:\b\w\33bdfc1cae7b2a38\modules\Identity\test\Service.Core.Test\AuthorizationCodeExchangeIntegrationTest.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by javiercn** [comment]
@ryanbrandenburg A couple of things:
Seems like these tests started failing on February.
Can you confirm (I can't tell for sure from the build logs) that they are failing on full framework?
Has .NET Framework been updated on the CI agents recently? (BTW, I just started seeing this error on AppVeyor too).

This is code that we haven't touch in months, so I'm a bit worried is a regression on a patch update or something similar in .NET framework.

**Comment by javiercn** [comment]
I'll be skipping the test for now

**Comment by ryanbrandenburg** [comment]
We had a period where we were cleaning up our history after ~ a month because our log files are 200mb and the disks were filling up, so there's no history older than that.

**Comment by javiercn** [comment]
This makes this issue way harder to debug :(. I haven't seen these tests fail in the past and we haven't changed the code in at least 6 months.

**Comment by ryanbrandenburg** [comment]
I spot checked some instances of this and only saw it in net461 test runs. To my knowledge we haven't updated .NET Framework on the CI agents.

**Comment by javiercn** [comment]
@ryanbrandenburg Are you confirming what I said before, that this is likely net461? 

Windows will update .net framework for you you automatically through windows update.

**Comment by ryanbrandenburg** [comment]
Yes, I was confirming that this is likely net461 specific.

**Comment by ryanbrandenburg** [comment]
@javiercn I think you had said that you wanted to remove these tests because they were low-value. Am I remembering that correctly?

**Comment by javiercn** [comment]
@ryanbrandenburg That's not the case.

**Comment by ryanbrandenburg** [comment]
CC @davidfowl who was asking about this.

**Comment by javiercn** [comment]
I've skipped all the tests affected by this and created a test experiment for it to run on the CI and see if we can repro it:
https://github.com/aspnet/Identity/pull/1686

**Comment by javiercn** [comment]
I don't think there's more action for preview2 here (other than watch the CI) or skip any additional test if I missed any.

**Comment by mkArtakMSFT** [comment]
Another hard-to-repro issue. Additional telemetry is added to identify the reason on the next failure. Moving this to the `rc` milestone to give it more time to show up. If this won't show up, we'll just close it during `rc` milestone.

**Comment by ryanbrandenburg** [comment]
The tests you added are [not running](http://aspnetci/viewLog.html?buildId=425741&buildTypeId=Lite_EntityFrameworkTest&tab=testsInfo).

**Comment by javiercn** [comment]
@ryanbrandenburg Can you be a bit more clear?

**Comment by ryanbrandenburg** [comment]
You added tests which we figured would prove your hypothesis about what was causing this, but because you did `[ConditionalFact(Skip = "...")]` they will never run, and we'll never figure out what's happening here.

**Comment by javiercn** [comment]
ah, ok. Thanks. Will fix it.

**Comment by javiercn** [comment]
@mkArtakMSFT I'm moving this to MQ. I'll take care of them next week as they are not product related issues nor anything we're shipping

**Comment by dougbu** [comment]
Once we've worked around this issue or it's fixed in .NET, should revert aspnet/Mvc@192e8073ee

**Comment by Eilon** [comment]
@javiercn - Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by javiercn** [comment]
@Eilon I think this has something to do with the Crypto layer. We can file a bug against dotnet for it, I'll have to spend some time producing a small repro, but will do so.

**Comment by Eilon** [comment]
@javiercn that sounds great, thanks! BTW you need to put a link in the "TODO" above.
