### ISSUE TITLE
AddDefaultUI() throws when using IdentityUser<T>

### ISSUE THREAD

**Issue by jeffhube** [aspnet/Identity#1690]
If your user and role inherit from IdentityUser\<T\> / IdentityRole\<T\> instead of IdentityUser / IdentityRole, then AddDefaultUI() throws.

Project to reproduce here: https://github.com/jeffhube/aspnet-identity-test

```csharp
public class ApplicationDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, Guid>
{
}

public class ApplicationUser : IdentityUser<Guid>
{
}

public class ApplicationRole : IdentityRole<Guid>
{
}

services.AddIdentity<ApplicationUser, ApplicationRole>()
    .AddEntityFrameworkStores<ApplicationDbContext>()
    .AddDefaultTokenProviders()
    .AddDefaultUI();
```

```
Unhandled Exception: System.ArgumentException: GenericArguments[0], 'IdentityTest.ApplicationUser', on 'Microsoft.AspNetCore.Identity.UI.IdentityDefaultUIConfigureOptions`1[TUser]' violates the constraint of type 'TUser'. ---> System.TypeLoadException: GenericArguments[0], 'IdentityTest.ApplicationUser', on 'Microsoft.AspNetCore.Identity.UI.IdentityDefaultUIConfigureOptions`1[TUser]' violates the constraint of type parameter 'TUser'.
   at System.RuntimeTypeHandle.Instantiate(RuntimeTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.Instantiate(Type[] inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   --- End of inner exception stack trace ---
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Microsoft.AspNetCore.Identity.IdentityBuilderUIExtensions.AddDefaultUI(IdentityBuilder builder)
   at IdentityTest.Startup.ConfigureServices(IServiceCollection services) in C:\Users\Jeff\Desktop\IdentityTest\Startup.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at IdentityTest.Program.BuildWebHost(String[] args) in C:\Users\Jeff\Desktop\IdentityTest\Program.cs:line 21
   at IdentityTest.Program.Main(String[] args) in C:\Users\Jeff\Desktop\IdentityTest\Program.cs:line 17
```

**Comment by HaoK** [comment]
So I think the main issue is that all the places in the UI that directly use the Id, i.e. https://github.com/aspnet/Identity/blob/641dfe3b629dfb4acd484d24d21d2040e1aeb31b/src/UI/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs#L100

need to be updated to use GetUserId, and more generally never access any of the IdentityUser properties directly, and then https://github.com/aspnet/Identity/blob/dev/src/UI/IdentityDefaultUIConfigureOptions.cs#L20
can be updated to remove the IdentityUser and allow any class.

This is basically the same issue as https://github.com/aspnet/Identity/issues/1679 but a more egregious example of why this needs to be fixed for 2.1, since breaking the ability for apps to customize the primary key and use the default ui is probably not going to fly...

cc @DamianEdwards @javiercn @ajcvickers @blowdart

**Comment by blowdart** [comment]
Considering that we've had a lot of comments on how hard it is already to change primary keys Hao is right, we can't make it even worse, not even by a little.

**Comment by mkArtakMSFT** [comment]
@kichalla can you please handle this, thanks!
