### ISSUE TITLE
Changing TKey broken in RC1

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/Identity#1773]
Do a normal File-New Project with individual auth. Modify the ApplicationDbContext like so:

```C#
public class ApplicationDbContext : IdentityDbContext<IdentityUser<Guid>, IdentityRole<Guid>, Guid>
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }
}
```

Attempt to use any Migrations command:
```
PM> add-migration Initial -Verbose
Using project 'IdentityRC1Core'.
Using startup project 'IdentityRC1Core'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\Stuff\IdentityRC1Core\IdentityRC1Core\bin\Debug\netcoreapp2.1\IdentityRC1Core.deps.json --additionalprobingpath C:\Users\avickers\.nuget\packages --additionalprobingpath C:\Users\avickers\.dotnet\NuGetFallbackFolder --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig C:\Stuff\IdentityRC1Core\IdentityRC1Core\bin\Debug\netcoreapp2.1\IdentityRC1Core.runtimeconfig.json "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.entityframeworkcore.tools\2.1.0-rc1-final\tools\netcoreapp2.0\any\ef.dll" migrations add Initial --json --verbose --no-color --prefix-output --assembly C:\Stuff\IdentityRC1Core\IdentityRC1Core\bin\Debug\netcoreapp2.1\IdentityRC1Core.dll --startup-assembly C:\Stuff\IdentityRC1Core\IdentityRC1Core\bin\Debug\netcoreapp2.1\IdentityRC1Core.dll --project-dir C:\Stuff\IdentityRC1Core\IdentityRC1Core\ --language C# --working-dir C:\Stuff\IdentityRC1Core --root-namespace IdentityRC1Core
Using assembly 'IdentityRC1Core'.
Using startup assembly 'IdentityRC1Core'.
Using application base 'C:\Stuff\IdentityRC1Core\IdentityRC1Core\bin\Debug\netcoreapp2.1'.
Using working directory 'C:\Stuff\IdentityRC1Core\IdentityRC1Core'.
Using root namespace 'IdentityRC1Core'.
Using project directory 'C:\Stuff\IdentityRC1Core\IdentityRC1Core\'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider...
Finding IWebHost accessor...
Using environment 'Development'.
Using application service provider from IWebHost accessor on 'Program'.
System.ArgumentException: GenericArguments[0], 'Microsoft.AspNetCore.Identity.IdentityUser', on 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserOnlyStore`6[TUser,TContext,TKey,TUserClaim,TUserLogin,TUserToken]' violates the constraint of type 'TUser'. ---> System.TypeLoadException: GenericArguments[0], 'Microsoft.AspNetCore.Identity.IdentityUser', on 'Microsoft.AspNetCore.Identity.UserStoreBase`5[TUser,TKey,TUserClaim,TUserLogin,TUserToken]' violates the constraint of type parameter 'TUser'.
   at System.RuntimeTypeHandle.Instantiate(RuntimeTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.Instantiate(Type[] inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   --- End of inner exception stack trace ---
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Microsoft.Extensions.DependencyInjection.IdentityEntityFrameworkBuilderExtensions.AddStores(IServiceCollection services, Type userType, Type roleType, Type contextType)
   at Microsoft.Extensions.DependencyInjection.IdentityEntityFrameworkBuilderExtensions.AddEntityFrameworkStores[TContext](IdentityBuilder builder)
   at IdentityRC1Core.Startup.ConfigureServices(IServiceCollection services) in C:\Stuff\IdentityRC1Core\IdentityRC1Core\Startup.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
An error occurred while accessing the IWebHost on class 'Program'. Continuing without the application service provider. Error: GenericArguments[0], 'Microsoft.AspNetCore.Identity.IdentityUser', on 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserOnlyStore`6[TUser,TContext,TKey,TUserClaim,TUserLogin,TUserToken]' violates the constraint of type 'TUser'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'ApplicationDbContext'.
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'ApplicationDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<ApplicationDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time. ---> System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to create an object of type 'ApplicationDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<ApplicationDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.
PM> 
```

**Comment by HaoK** [comment]
Yeah not good, is this something specific new in rc1 that worked in preview2?

**Comment by HaoK** [comment]
We do have functional tests in identity exercising these kinds of scenarios, so is it something in how the migration is generated now?

**Comment by ajcvickers** [comment]
I didn't try it in preview2. It's not related to the generated migration.

**Comment by ajcvickers** [comment]
I suspect something internally is constrained to `IdentityUser` instead of `IdentityUser<TKey>`.

**Comment by HaoK** [comment]
Ok I still have preview2 bits, I'll try it

**Comment by HaoK** [comment]
System.ArgumentException: GenericArguments[0], 'Microsoft.AspNetCore.Identity.IdentityUser', on 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserOnlyStore`6[TUser,TContext,TKey,TUserClaim,TUserLogin,TUserToken]' violates the constraint of type 'TUser'. ---> System.TypeLoadException: GenericArguments[0], 'Microsoft.AspNetCore.Identity.IdentityUser', on 'Microsoft.AspNetCore.Identity.UserStoreBase`5[TUser,TKey,TUserClaim,TUserLogin,TUserToken]' violates the constraint of type parameter 'TUser'.

Well its a problem that it found the UserOnlyStore, what's the rest of your startup look like?

**Comment by ajcvickers** [comment]
That was it. I didn't update my startup to:
```C#
services.AddDefaultIdentity<IdentityUser<Guid>>()
                .AddEntityFrameworkStores<ApplicationDbContext>();
```
Once it did this it worked. More stuff for the document!

**Comment by HaoK** [comment]
Whew :)

**Comment by HaoK** [comment]
That would have been a pretty big regression

**Comment by HaoK** [comment]
But yeah changing primary keys still requires a bunch of coordinated changes :/

**Comment by ajcvickers** [comment]
There's also this bug in EF: https://github.com/aspnet/EntityFrameworkCore/issues/11832, but as I am writing the docs I am settling on this approach anyway, which seems to work:
* Do it before you create the database; changing key types in an existing database is a world of pain
* Remove the initial-migration (Just call `Remove-Migration`)
* Change the key type of your context and user _and modify Startup to reflect this change_.
* Run `Update-Database`.

**Comment by jtheisen** [comment]
The main problem here is that the error messages aren't that helpful. You only get

    An error occurred while accessing the IWebHost on class 'Program'. Continuing without the application service provider.

in the console and then a failure to instantiate the context as the connection string isn't available.

Perhaps that error that occurred there has a message on its own that could be displayed as well?
