### ISSUE TITLE
Test failure: CanLogInWithTwoFactorAuthentication_WithGlobalAuthorizeFilter

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Identity#1922]
This test [fails](http://aspnetci/viewLog.html?buildId=533610&buildTypeId=Releases_22xPublic_HighSierraOsxUniverse) occasionally with the following error:
```
System.IO.IOException : Undefined error: 0
   at System.IO.FileSystemWatcher.RunningInstance.Start()
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionDescriptorChangeProvider.GetChangeToken()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider..ctor(IEnumerable`1 actionDescriptorProviders, IEnumerable`1 actionDescriptorChangeProviders)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   at Identity.DefaultUI.WebSite.StartupBase`2.Configure(IApplicationBuilder app, IHostingEnvironment env)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateServer(IWebHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
   at Microsoft.AspNetCore.Identity.FunctionalTests.LoginTests`2.CanLogInWithTwoFactorAuthentication_WithGlobalAuthorizeFilter()
--- End of stack trace from previous location where exception was thrown ---
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC @Eilon (because the bot doesn't know who else to pick)

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CanLogInAfterConfirmingEmail [failed with about the same error](http://aspnetci/viewLog.html?buildId=533610&buildTypeId=Releases_22xPublic_HighSierraOsxUniverse) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CanSetPasswordWithExternalLogin [failed with about the same error](http://aspnetci/viewLog.html?buildId=534596&buildTypeId=XPlat_HighSierraOsxUniverse) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CanLogInWithTwoFactorAuthentication_WithGlobalAuthorizeFilter [failed with about the same error](http://aspnetci/viewLog.html?buildId=535157&buildTypeId=Releases_22xPublic_HighSierraOsxUniverse) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CanLogInWithTwoFactorAuthentication_WithGlobalAuthorizeFilter [failed with about the same error](http://aspnetci/viewLog.html?buildId=535338&buildTypeId=Releases_22xPublic_HighSierraOsxUniverse) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
CanLogInWithTwoFactorAuthentication_WithGlobalAuthorizeFilter [failed with about the same error](http://aspnetci/viewLog.html?buildId=535418&buildTypeId=Releases_22xPublic_HighSierraOsxUniverse) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
CanLogInWithTwoFactorAuthentication_WithGlobalAuthorizeFilter [failed with about the same error](http://aspnetci/viewLog.html?buildId=536059&buildTypeId=Releases_22xPublic_HighSierraOsxUniverse) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
CanLogInWithTwoFactorAuthentication_WithGlobalAuthorizeFilter [failed with about the same error](http://aspnetci/viewLog.html?buildId=536615&buildTypeId=XPlat_HighSierraOsxUniverse) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by Eilon** [comment]
@mkArtakMSFT - can you assign? Call stack looks related to Razor Pages.

**Comment by aspnet-hello** [comment]
CanLogInWithTwoFactorAuthentication_WithGlobalAuthorizeFilter [failed with about the same error](http://aspnetci/viewLog.html?buildId=538213&buildTypeId=XPlat_HighSierraOsxUniverse) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
CanLogInWithTwoFactorAuthentication_WithGlobalAuthorizeFilter [failed with about the same error](http://aspnetci/viewLog.html?buildId=538825&buildTypeId=XPlat_HighSierraOsxUniverse) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
@mkArtakMSFT was this resolved? If so how? Please assign someone to find out.

**Comment by mkArtakMSFT** [comment]
@javiercn, can you please look into this and close if this is resolved already. Otherwise - just come up with a fix please.

**Comment by javiercn** [comment]
I checked and it seems like we did. Given that all the views are precompiled. Would it be problematic if we remove all the file providers from razor view engine options? That way there wouldn’t be any file watching going on, based on what I see on DefaultRazorViewEngineFileProviderAccessor. Does that make sense @pranavkm

**Comment by pranavkm** [comment]
> Would it be problematic if we remove all the file providers from razor view engine options? 

Think the compiler throws if you have no fileproviders. You might have to hack it a bit. More specifically we don't watch for files in Release builds which is usually what exhausts file descriptors.

**Comment by javiercn** [comment]
@pranavkm would it be a problem if we just add a bogus one instead? The callstack looks pretty descriptive to me.

**Comment by pranavkm** [comment]
Adding a `CompositeFileProvider` that contains a single `NullFileProvider` might not throw. Highlighting the relevant pieces

* https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Razor/Internal/DefaultRazorViewEngineFileProviderAccessor.cs#L21-L24
* https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Razor/Internal/RazorViewCompilerProvider.cs#L53-L60

**Comment by javiercn** [comment]
https://github.com/aspnet/Identity/commit/95bc2518486554be18191211e70a2ac8e8765ed3
