### ISSUE TITLE
Error Building Fresh Clone

### ISSUE THREAD

**Issue by joshpearce** [aspnet/Identity#364]
Running build.cmd on a fresh clone yields two errors:

Error 1:
```
CALL packages\KoreBuild\build\kvm use default -runtime CLR -x86
Console-Write-Error : Cannot find kre-clr-win-x86.default, do you need to run 'kvm install default'?
```
Error 2:
```
Using Project dependency Microsoft.AspNet.Identity 3.0.0-t150216153340 for Asp.Net,Version=v5.0
  Copying source code from Project dependency Microsoft.AspNet.Identity
    Source Z:\Dev\Cupcake\3rdsrc\Identity\src\Microsoft.AspNet.Identity\project.json
    Target Z:\Dev\Cupcake\3rdsrc\Identity\src\Microsoft.AspNet.Identity\bin\output\approot\src\Microsoft.AspNet.Identity

Time elapsed 00:00:13.2158520
warn: Could not find a part of the path 'Z:\Dev\Cupcake\3rdsrc\Identity\src\Microsoft.AspNet.Identity\bin\Debug'.
verbose: Stack trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchO
ption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at View258561f8bc1c4c7d913dbe88704a8fce.PathResolver.PerformWildcardSearchInternal(String basePath, String searchPath
, String& normalizedBasePath) in c:\Users\joshuapearce\AppData\Local\Temp\e3141a9ef72441ad8c135d7fbbd26b88-1.cs:line 103
4
   at View258561f8bc1c4c7d913dbe88704a8fce.PathResolver.PerformWildcardSearch(String basePath, String searchPath) in c:\
Users\joshuapearce\AppData\Local\Temp\e3141a9ef72441ad8c135d7fbbd26b88-1.cs:line 1005
   at View258561f8bc1c4c7d913dbe88704a8fce._Files.PerformSearch(String pattern) in c:\Users\joshuapearce\AppData\Local\T
emp\e3141a9ef72441ad8c135d7fbbd26b88-1.cs:line 445
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__81`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at View258561f8bc1c4c7d913dbe88704a8fce._Files.Scan() in c:\Users\joshuapearce\AppData\Local\Temp\e3141a9ef72441ad8c1
35d7fbbd26b88-1.cs:line 429
   at View258561f8bc1c4c7d913dbe88704a8fce._Files.System.Collections.Generic.IEnumerable<System.String>.GetEnumerator()
in c:\Users\joshuapearce\AppData\Local\Temp\e3141a9ef72441ad8c135d7fbbd26b88-1.cs:line 413
   at View258561f8bc1c4c7d913dbe88704a8fce.<>c__DisplayClass77.<RenderViewLevel0>b__48() in c:\Users\joshuapearce\AppDat
a\Local\Temp\e3141a9ef72441ad8c135d7fbbd26b88-1.cs:line 2288
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View258561f8bc1c4c7d913dbe88704a8fce.<RenderViewLevel0>b__39() in c:\Users\joshuapearce\AppData\Local\Temp\e3141a9
ef72441ad8c135d7fbbd26b88-1.cs:line 1273
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View258561f8bc1c4c7d913dbe88704a8fce.<RenderViewLevel0>b__3a() in c:\Users\joshuapearce\AppData\Local\Temp\e3141a9
ef72441ad8c135d7fbbd26b88-1.cs:line 1290
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View258561f8bc1c4c7d913dbe88704a8fce.<RenderViewLevel0>b__3b() in c:\Users\joshuapearce\AppData\Local\Temp\e3141a9
ef72441ad8c135d7fbbd26b88-1.cs:line 1307
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at View258561f8bc1c4c7d913dbe88704a8fce.<RenderViewLevel0>b__33() in c:\Users\joshuapearce\AppData\Local\Temp\e3141a9
ef72441ad8c135d7fbbd26b88-1.cs:line 1163
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
```

**Comment by joshpearce** [comment]
Closing: I can clone and build this solution successfully using the latest Visual Studio 2015 CTP and the 3.0.0-beta3 tag.
