### ISSUE TITLE
Problem with names on queries with Identity and Guid primary keys

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Identity#448]
I'm not sure why this is failing. I see a weird "`" in some names that may be the issue.
Using CTP6 - Beta3
EF Package: "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta3"
Framework: CoreCLR (aspnetcore50)
Platform: Windows

I setted up so I only have : 
```
public class ApplicationDbContext : IdentityDbContext<ApplicationUser, IdentityRole<Guid>,Guid>
{ 
    //... 
}

protected override void OnModelCreating(ModelBuilder builder)
{

    base.OnModelCreating(builder);

    foreach (var entityType in builder.Model.EntityTypes)
    {
        var table = entityType.Relational().Table;
        if (table.StartsWith("AspNet"))
            entityType.Relational().Table = $"Identity{table.Substring(6)}"; // this should be the default.
    }
}

public override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.CreateTable("IdentityUsers",
        c => new
            {
                Id = c.Guid(nullable: false),
                AccessFailedCount = c.Int(nullable: false),
                ConcurrencyStamp = c.String(),
                Email = c.String(),
                EmailConfirmed = c.Boolean(nullable: false),
                LockoutEnabled = c.Boolean(nullable: false),
                LockoutEnd = c.DateTimeOffset(),
                NormalizedEmail = c.String(),
                NormalizedUserName = c.String(),
                PasswordHash = c.String(),
                PhoneNumber = c.String(),
                PhoneNumberConfirmed = c.Boolean(nullable: false),
                SecurityStamp = c.String(),
                TwoFactorEnabled = c.Boolean(nullable: false),
                UserName = c.String()
            })
        .PrimaryKey("PK_IdentityUsers", t => t.Id);
            
    migrationBuilder.CreateTable("IdentityRoleClaims",
        c => new
            {
                Id = c.Int(nullable: false, identity: true),
                ClaimType = c.String(),
                ClaimValue = c.String(),
                IdentityRole1Id = c.Guid(name: "IdentityRole`1Id"), // NOTE: Name
                RoleId = c.Guid(nullable: false)
            })
        .PrimaryKey("PK_IdentityRoleClaims", t => t.Id);
            
    migrationBuilder.CreateTable("IdentityRoles",
        c => new
            {
                Id = c.Guid(nullable: false),
                ConcurrencyStamp = c.String(),
                Name = c.String(),
                NormalizedName = c.String()
            })
        .PrimaryKey("PK_IdentityRoles", t => t.Id);
            
    migrationBuilder.CreateTable("IdentityUserClaims",
        c => new
            {
                Id = c.Int(nullable: false, identity: true),
                ClaimType = c.String(),
                ClaimValue = c.String(),
                UserId = c.Guid(nullable: false)
            })
        .PrimaryKey("PK_IdentityUserClaims", t => t.Id);
            
    migrationBuilder.CreateTable("IdentityUserLogins",
        c => new
            {
                LoginProvider = c.String(),
                ProviderKey = c.String(),
                ProviderDisplayName = c.String(),
                UserId = c.Guid(nullable: false)
            })
        .PrimaryKey("PK_IdentityUserLogins", t => new { t.LoginProvider, t.ProviderKey });
            
    migrationBuilder.CreateTable("IdentityUserRoles",
        c => new
            {
                UserId = c.Guid(nullable: false),
                RoleId = c.Guid(nullable: false),
                IdentityRole1Id = c.Guid(name: "IdentityRole`1Id") // NOTE: Name
            })
        .PrimaryKey("PK_IdentityUserRoles", t => new { t.UserId, t.RoleId });
            
    migrationBuilder.AddForeignKey(
        "IdentityRoleClaims",
        "FK_IdentityRoleClaims_IdentityRoles_IdentityRole`1Id", // NOTE: Name
        new[] { "IdentityRole`1Id" },
        "IdentityRoles",
        new[] { "Id" },
        cascadeDelete: false);
            
    migrationBuilder.AddForeignKey(
        "IdentityRoleClaims",
        "FK_IdentityRoleClaims_IdentityRoles_RoleId",
        new[] { "RoleId" },
        "IdentityRoles",
        new[] { "Id" },
        cascadeDelete: false);
            
    migrationBuilder.AddForeignKey(
        "IdentityUserClaims",
        "FK_IdentityUserClaims_IdentityUsers_UserId",
        new[] { "UserId" },
        "IdentityUsers",
        new[] { "Id" },
        cascadeDelete: false);
            
    migrationBuilder.AddForeignKey(
        "IdentityUserLogins",
        "FK_IdentityUserLogins_IdentityUsers_UserId",
        new[] { "UserId" },
        "IdentityUsers",
        new[] { "Id" },
        cascadeDelete: false);
            
    migrationBuilder.AddForeignKey(
        "IdentityUserRoles",
        "FK_IdentityUserRoles_IdentityRoles_IdentityRole`1Id", // NOTE: Name
        new[] { "IdentityRole`1Id" },
        "IdentityRoles",
        new[] { "Id" },
        cascadeDelete: false);
}

```
Steps to get into this state:
ef migration apply 0
ef migration remove (times needed until no snapshot)
DELETED DATABASE
ef migration add identity
k ef migration apply
```
Using context 'ApplicationDbContext'.
Creating migration history table.
Applying migration '201504181209199_identity'.
System.Data.SqlClient.SqlException: There is already an object named 'IdentityUsers' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInA
ction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectio
nLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, B
ulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean as
yncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boo
lean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.<>c__DisplayClass7_0.<ExecuteNonQuery>b__0()
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.Execute(RelationalConnection connection, Func`1 action)
   at Microsoft.Data.Entity.Relational.Migrations.Infrastructure.Migrator.ExecuteStatementsWithinTransaction(IEnumerable
`1 sqlStatements, RelationalConnection connection)
   at Microsoft.Data.Entity.Relational.Migrations.Infrastructure.Migrator.ApplyMigration(Int32 index, Boolean simulate)
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.Data.Entity.Relational.Migrations.Infrastructure.Migrator.ApplyMigrations(Int32 targetMigrationIndex, Bo
olean simulate)
   at Microsoft.Data.Entity.Commands.MigrationTool.ApplyMigration(String migrationName, String contextTypeName)
   at Microsoft.Data.Entity.Commands.Program.ApplyMigration(String migration, String context)
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
ClientConnectionId:5c4ee1b3-8fad-4f2c-98fc-dee820105411
Error Number:2714,State:6,Class:16
```

**Comment by Bartmax** [comment]
There is already an object named 'IdentityUsers' was fixed removing EnsureCreated on dbcontext constructor (tried to add it twice I think)

other issue is how it generated field that shouldn't be there. I modified the snapshot, the migration code and executed and got a correct db. 

now I have created another migration with the offending code that I will leave on the snapshot but remove the Up code: (this should not be generated) - bug?

```
public override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn("IdentityRoleClaims", "IdentityRole`1Id", c => c.Guid());
            
            migrationBuilder.AddColumn("IdentityUserRoles", "IdentityRole`1Id", c => c.Guid());
            
            migrationBuilder.AddForeignKey(
                "IdentityRoleClaims",
                "FK_IdentityRoleClaims_IdentityRoles_IdentityRole`1Id",
                new[] { "IdentityRole`1Id" },
                "IdentityRoles",
                new[] { "Id" },
                cascadeDelete: false);
            
            migrationBuilder.AddForeignKey(
                "IdentityUserRoles",
                "FK_IdentityUserRoles_IdentityRoles_IdentityRole`1Id",
                new[] { "IdentityRole`1Id" },
                "IdentityRoles",
                new[] { "Id" },
                cascadeDelete: false);
        }
```

**Comment by Bartmax** [comment]
And after that, it still explodes with:
```
InvalidCastException: Invalid cast from 'System.String' to 'System.Guid'.
System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
```

Going back to string key for now.

**Comment by Bartmax** [comment]
I identified the problem so I will close this one and create a new issue with the real problem.
