### ISSUE TITLE
ToTable Rename of Identity Models causes migration error

### ISSUE THREAD

**Issue by dansiegel** [aspnet/Identity#551]
When trying to rename the Entity tables a ModelItemNotFoundException is thrown when a new migration is attempted. This occurs whether the base migration is left in place or not. The project is 100% the boiler plate project created when you start a new project with Individual Accounts. The only change is shown below.
```csharp
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            builder.Entity<ApplicationUser>().ToTable( "Users" );
            builder.Entity<IdentityRole>().ToTable( "Roles" );
            builder.Entity<IdentityRoleClaim>().ToTable( "RoleClaims" );
            builder.Entity<IdentityUserRole>().ToTable( "UserRoles" );
        }
    }
```

PS C:\Repos\Test & Demo\WebApplication2\src\WebApplication2> dnx . ef migration add Test
Using context 'ApplicationDbContext'.
Microsoft.Data.Entity.Metadata.ModelItemNotFoundException: The entity type 'Microsoft.AspNet.Identity.EntityFramework.IdentityUserRole' requires a key to be defined.
   at Microsoft.Data.Entity.Metadata.EntityTypeExtensions.GetPrimaryKey(IEntityType entityType)
   at Microsoft.Data.Entity.Migrations.Infrastructure.ModelDiffer.<Add>d__25.MoveNext()
   at Microsoft.Data.Entity.Migrations.Infrastructure.ModelDiffer.<DiffCollection>d__47\`1.MoveNext()
   at System.Linq.Enumerable.\<ConcatIterator>d__1\`1.MoveNext()
   at System.Linq.Enumerable.\<ConcatIterator>d__1\`1.MoveNext()
   at System.Linq.Enumerable.\<ConcatIterator>d__1\`1.MoveNext()
   at Microsoft.Data.Entity.Migrations.Infrastructure.ModelDiffer.Sort(IEnumerable\`1 operations, ModelDifferContext diffContext)
   at Microsoft.Data.Entity.Migrations.Infrastructure.ModelDiffer.GetDifferences(IModel source, IModel target)
   at Microsoft.Data.Entity.Commands.Migrations.MigrationScaffolder.ScaffoldMigration(String migrationName, String rootNamespace)
   at Microsoft.Data.Entity.Commands.MigrationTool.AddMigration(String migrationName, String contextTypeName, String startupAssemblyName, String rootNamespace, String projectDir)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass12_0.<AddMigration>b__0()
   at Microsoft.Data.Entity.Commands.Program.Execute(String startupProject, Func\`1 invoke)
   at Microsoft.Data.Entity.Commands.Program.AddMigration(String name, String context, String startupProject)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass10_1.\<Main>b__7()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Data.Entity.Commands.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List\`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)

**Comment by HaoK** [comment]
@divega any ideas what might cause this error?

**Comment by HaoK** [comment]
@AndriySvyryd Should the call to ToTable erase all the previous configuration from the base.OnCreating call?

**Comment by AndriySvyryd** [comment]
I don't see anything wrong with this code, so it's probably a bug in EF

**Comment by divega** [comment]
@AndriySvyryd Thanks for taking a look. That is what we thought. Could you use this as a start point for a repro? The base class is [IdentityDbContext](https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNet.Identity.EntityFramework/IdentityDbContext.cs).

**Comment by rustd** [comment]
@AndriySvyryd Is this going to make it in for beta8?

**Comment by AndriySvyryd** [comment]
@rustd Not currently. Talk to @divega if you think it should.

**Comment by divega** [comment]
@AndriySvyryd could @smitpatel work on this?

**Comment by AndriySvyryd** [comment]
@divega Yes

**Comment by divega** [comment]
Assigned.

**Comment by smitpatel** [comment]
The entity added by base OnModelConfiguring is `IdentityUserRole<TKey>` where `TKey` is string, so entity type name for EF is `IdentityUserRole<string>` which is different from `IdentityUserRole` (used for table rename above) therefore EF adds a new entity for that. For all other classes EF assigns PK by convention but fails to do so for `IdentityUserRole` and throws exception.

**Comment by divega** [comment]
@HaoK @rustd this is a bug on Identity. @smitpatel did the analysis and it turn out that on `IdentityDbContext<...>.OnModelCreating()` we are configuring `IdentityUserClaim<TKey>`, `IdentityRoleClaim<TKey>`, `IdentityUserRole<TKey>` and `IdentityUserLogin<TKey>` as the generic entities themselves. We actually don't use the non generic versions of those classes anywhere so if a user tries to configure those as in the description of the issue, those will be completely different entities.

Note that the symptom observed by the customer (the exception) is due to the fact that `IdentityUserRole` doesn't have a key that can be inferred by a code first convention, but that is not the main bug.

I believe there are two possible solutions:

1. Get rid of the non-generic versions of those entity types. The would mean that customers that want to refer to them would need to use the generics always and wouldn't erroneously use types that Identity won't use.

2. Templatize the IdentityDbContext on these types similarily to how we do it for `TUser` and `TRole`. I would look something like this:

 ``` C#
public class IdentityDbContext<TUser, TRole, 
        TUserClaim, TRoleClaim, TUserRole, TUserLogin, 
        TKey> : DbContext 
    where TUser : IdentityUser<TKey> 
    where TRole : IdentityRole<TKey>
    where TUserClaim: IdentityUserClaim<TKey>
    where TRoleClaim: IdentityRoleClaim<TKey>
    where TUserRole: IdentityUserRole<TKey>
    where TUserLogin: IdentityUserLogin<TKey>
    where TKey : IEquatable<TKey> 
{
 ```
From a certain angle, the second option is cleaner, but I suspect it would leak the generic arguments into the `UserStore` and `RoleStore` types and to an `AddIdentity()` overload.

**Comment by divega** [comment]
I talked to @HaoK and option two is apparently how things used to look like in Identity 2.0, but he prefers option one to avoid the 4 additional generic arguments to be created in store types and `AddIdentity()`

**Comment by divega** [comment]
Moving to @HaoK and beta8. Thanks @smitpatel for the analysis.

**Comment by HaoK** [comment]
Looks like these were already nuked in a previous beta... so nothing to be done now

**Comment by HaoK** [comment]
only identityRole and IdentityUser remain

**Comment by divega** [comment]
Thanks. Good to know. I still wonder how providers that don't support generics would handle customization of the key type, e.g. the EF6 provider that @cherrydev worked on had to use non-generic entity types.

**Comment by joshmouch** [comment]
I'm not sure sure what "nuked in previous beta" means?  I have the latest versions and I'm still getting this exception.

**Comment by joshmouch** [comment]
I'll create another ticket for this, but I prefer Identity 2.0 signature with the extra generic arguments.  It allows us to extend every table, as needed.

This is actually a huge pain for me, as I cannot upgrade to Identity 3.0 right now because those generic type arguments are missing.
