### ISSUE TITLE
Reduce contention for `model` database between tests

### ISSUE THREAD

**Issue by dougbu** [aspnet/Identity#678]
Errors on the CI machines indicate multiple tests are competing for the same resources. Though we initially thought the issue was reuse of connection strings between test classes, the problematic database is actually `model`. Most likely fix would be to use an xUnit test fixture to create and delete databases and to allow individual tests to run in any order without breaking initial state assumptions. (Tests currently drop and recreate databases between tests, significantly increasing contention for the `model` database.)

For example,
```
System.Data.SqlClient.SqlException : Could not obtain exclusive lock on database 'model'. Retry the operation later.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, Boolean openConnection, Boolean closeConnection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, Boolean manageConnection)
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommandExtensions.ExecuteNonQuery(IEnumerable`1 commands, IRelationalConnection connection)
   at Microsoft.Data.Entity.Storage.Internal.SqlServerDatabaseCreator.Create()
   at Microsoft.Data.Entity.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.Data.Entity.Infrastructure.DatabaseFacade.EnsureCreated()
   at Microsoft.AspNet.Identity.EntityFramework.Test.DefaultPocoTest.CreateContext(Boolean ensureCreated) in C:\BuildAgent\ba\e70224f4ea5e88a1\Identity\test\Microsoft.AspNet.Identity.EntityFramework.Test\DefaultPocoTest.cs:line 26
   at Microsoft.AspNet.Identity.EntityFramework.Test.DefaultPocoTest.<CanIncludeRoleClaimsTest>d__10.MoveNext() in C:\BuildAgent\ba\e70224f4ea5e88a1\Identity\test\Microsoft.AspNet.Identity.EntityFramework.Test\DefaultPocoTest.cs:line 195
```
Same thing for `UserStoreGuidTest.AddDupeEmailAllowedByDefault`. That stack trace goes up to:
```
...
   at Microsoft.AspNet.Identity.EntityFramework.Test.SqlStoreTestBase`3.CreateContext(Boolean delete) in C:\BuildAgent\ba\e70224f4ea5e88a1\Identity\test\Microsoft.AspNet.Identity.EntityFramework.Test\SqlStoreTestBase.cs:line 95
   at Microsoft.AspNet.Identity.EntityFramework.Test.SqlStoreTestBase`3.CreateTestContext() in C:\BuildAgent\ba\e70224f4ea5e88a1\Identity\test\Microsoft.AspNet.Identity.EntityFramework.Test\SqlStoreTestBase.cs:line 101
   at Microsoft.AspNet.Identity.Test.UserManagerTestBase`3.CreateManager(Object context, IServiceCollection services, Action`1 configureServices) in C:\BuildAgent\ba\e70224f4ea5e88a1\Identity\test\Shared\UserManagerTestBase.cs:line 64
   at Microsoft.AspNet.Identity.Test.UserManagerTestBase`3.<AddDupeEmailAllowedByDefault>d__44.MoveNext() in C:\BuildAgent\ba\e70224f4ea5e88a1\Identity\test\Shared\UserManagerTestBase.cs:line 711
```

**Comment by divega** [comment]
@natemcmaster will take a look today.

**Comment by dougbu** [comment]
This happened again with two different tests:
```
Test collection for Microsoft.AspNet.Identity.EntityFramewo…PocoTest (1): Microsoft.AspNet.Identity.EntityFramework.Test (1)
  CustomPocoTest.CanCreateUserInt
```
and
```
Test collection for Microsoft.AspNet.Identity.EntityFramewo…toreTest (1): Microsoft.AspNet.Identity.EntityFramework.Test (1)
  UserStoreTest.AddDupeEmailAllowedByDefault
```

**Comment by divega** [comment]
@moozzyk @Tratcher heads up that with this fixed, Identity tests more stable on CI. Let us know if that isn't the case.

**Comment by moozzyk** [comment]
@divega @natemcmaster :clap:
