### ISSUE TITLE
App.Use() custom authentication + Integration testing with TestServer does not seem to configure authentication handler properly?

### ISSUE THREAD

**Issue by stefanhendriks** [aspnet/Identity#846]
We recently upgraded to RC2. In our app we have this in our startup.cs:

```
app.Use(async (context, next) =>
			{
				HttpRequest request = context.Request;

				if (request.Headers.ContainsKey(ApiSecretHeader))
				{
					string key = request.Headers[ApiSecretHeader];
					var allowedKeys = context.RequestServices.GetRequiredService<IOptions<ApiKeySettings>>().Value.Keys;

					if (allowedKeys.ContainsKey(key))
					{
						var identity = new ClaimsIdentity("Custom");
						identity.AddClaim(new Claim(ClaimTypes.Name, key));
						identity.AddClaim(new Claim(ClaimTypes.Role, allowedKeys[key]));
						context.User = new ClaimsPrincipal(identity);
					}
				}

				await next.Invoke();

			});
```
This basically checks if a header is present, if the value of the header is known to us, and if so it is allowed to execute the request. (ie it is authorized).

When normally booting our app, and testing this, it works fine. I get a `401` when expected or the request is being processed.

However, I also had an integration test set up. I use a `TestFixture` which looks like this:

```
public class TestServerFixture : IDisposable
    {
		public TestServer server { get; }

		public HttpClient client { get; }

	    public TestServerFixture()
	    {
			// Arrange
			var builder = new WebHostBuilder()
				.UseEnvironment("Development")
				.UseStartup<TestPortalStartup>() // TestPortalStartup is extending from Portal so we can hook up some mocks instead of 'real' objects.
				.UseKestrel()
				.UseContentRoot(Path.GetFullPath(
					Path.Combine(PlatformServices.Default.Application.ApplicationBasePath, "../../../../", "My.App.Namespace")
				))
				.UseWebRoot(Path.GetFullPath(
					Path.Combine(PlatformServices.Default.Application.ApplicationBasePath, "../../../../", "My.App.Namespace")
				));

			server = new TestServer(builder);
			client = server.CreateClient();
		}

		public void Dispose()
	    {
			server.Dispose();
			client.Dispose();
	    }
```

Now, when I want to test if an URL is being tested if it is authorized or not (ie, I expect a 401) I get the message `Result Message:	No authentication handler is configured to handle the scheme: Automatic`, full trace is:
```
Test Name:	<snip>.AuthenticationControllerTest.Url_Should_Be_Using_Authorization_Token(url: "/api/authentication/login")
Test FullName:	<snip>.AuthenticationControllerTest.Url_Should_Be_Using_Authorization_Token(769d832d772c1782a97e5f1780a398243fd8d612)
Test Source:	<snip>AuthenticationControllerTest.cs : line 26
Test Outcome:	Failed
Test Duration:	0:00:00.455

Result StackTrace:	
at Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager.<ChallengeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.<ExecuteResultAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeResultAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.<InvokeActionAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at <snip>.Startup.<>c.<<Configure>b__7_0>d.MoveNext() in <snip>Startup.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.TestHost.ClientHandler.<>c__DisplayClass3_0.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.TestHost.ClientHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at <snip>.AuthenticationControllerTest.<Url_Should_Be_Using_Authorization_Token>d__1.MoveNext() in C:\<snip>AuthenticationControllerTest.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 227
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
Result Message:	No authentication handler is configured to handle the scheme: Automatic


```

However, that is ONLY in the tests. As said, when booting up the app myself and simply testing via Postman for instance, it works fine.

The test looks like this:
```
public class AuthenticationControllerTest : AbstractControllerIntegrationTest
    {
	    public AuthenticationControllerTest(TestServerFixture testServerFixture) : base(testServerFixture)
	    {
	    }

		[Theory]
		[InlineData("/api/authentication/login")]
		[InlineData("/api/authentication/logout")]
		[InlineData("/api/authentication/password/requestreset")]
		[InlineData("/api/authentication/password/reset")]
		public async Task Url_Should_Be_Using_Authorization_Token(string url)
		{
			HttpRequestMessage httpRequestMessage = new HttpRequestMessage(HttpMethod.Post, url);

			// empty request passed here, because it won't reach the controller anyway
			var response = await client.SendAsync(httpRequestMessage);

			Assert.Equal(HttpStatusCode.Unauthorized, response.StatusCode);
		}
...

}
```

I have tried to add `UseAuthenticationCookies` to check if it made any difference. It did make the `No Authentication handler is configured` message go away, but it also resulted in a Redirect to a non-existing URL. It made me feel uneasy though, since this problem is only applicable for my integration tests and I don't think adding such code to satisfy the Integration tests would solve anything.

I have also tried using `UseIdentity` and after some fiddling I get at the same point where I get a Redirect instead of a 401.

What puzzles me is that this behavior is different for the Integration test vs running it for real. I would expect the TestServer that boots, to simply use the same configuration.

Any clues?

**Comment by blowdart** [comment]
This is not an Identity issue. Identity, is basically our membership system. Please add an issue to the Security repo.
