### ISSUE TITLE
UpperInvariantLookupNormalizer.Normalize() can throw SEHException on Windows Server 2016 TP5

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Identity#882]
Under certain conditions, `UpperInvariantLookupNormalizer.Normalize()` can throw `System.Runtime.InteropServices.SEHException` on Windows Server 2016 TP5.
- Typically, the API works the first time a Windows Container is run, but fails on subsequent runs until Windows is restarted.
- Sometimes the API never fails, no matter how many containers are run.
- We believe the root cause is a Windows bug, and ASP.NET and CoreFx should not need any changes.

Please keep this issue open for tracking until the Windows bug is fixed.
## Workaround

As a temporary workaround, the `UpperInvariantLookupNormalizer` can be replaced with a similar implemention which skips the call to `Normalize()`.

First, add a nested class to `Startup.cs`:

```
private class MyLookupNormalizer : Microsoft.AspNetCore.Identity.ILookupNormalizer
{
    public string Normalize(string key) => key?.ToUpperInvariant();
}        
```

Then add a line to `ConfigureServices(IServiceCollection services)`:

```
services.AddScoped<Microsoft.AspNetCore.Identity.ILookupNormalizer, MyLookupNormalizer>();
```
## Exception

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at Interop.mincore.NormalizeString(Int32 normForm, String source, Int32 sourceLength, Char[] destenation, Int32 destenationLength)
   at System.StringNormalizationExtensions.Normalize(String strInput, NormalizationForm normalizationForm)
   at Microsoft.AspNetCore.Identity.UpperInvariantLookupNormalizer.Normalize(String key)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName)
   at MusicStore.Models.SampleData.<CreateAdminUser>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at MusicStore.Models.SampleData.CreateAdminUser(IServiceProvider serviceProvider)
   at MusicStore.Models.SampleData.<InitializeMusicStoreDatabaseAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at MusicStore.Models.SampleData.InitializeMusicStoreDatabaseAsync(IServiceProvider serviceProvider, Boolean createUsers)
   at MusicStore.Startup.Configure(IApplicationBuilder app)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at MusicStore.Program.Main(String[] args)
```
## Related

https://github.com/dotnet/corefx/issues/9650

**Comment by HaoK** [comment]
closing as linked bug has been closed as well
